---
- name: Converge
  hosts: all
  gather_facts: true
  remote_user: root
  tasks:
    # TODO: resolve deps
    - name: "Testing -- asdf"
      include_role:
        name: components
      vars:
        role_component:
          components:
            - asdf
