---
# CMD
- block:
    - name: '[cmd] {{ current_component|upper }} render {{ prefix }} {{ type }}'
      become: false
      copy:
        dest: '{{ component_render_dir }}/{{ prefix }}_{{ type }}_{{ current_component
          }}.yml'
        content: '{{ content | to_nice_yaml }}'
        force: true
      delegate_to: localhost
    - include_tasks: '{{ component_render_dir }}/{{ prefix }}_{{ type }}_{{ current_component
        }}.yml'
  tags: always
