---
# TEMPLATE
- block:
  - name: "[template] {{ template.name|upper }} local facts"
    set_fact:
      template_src:   "{{ template.template | default('') }}"
      template_dest:  "{{ template.dest  | default('') }}"
      template_owner: "{{ template.owner | default(role_component.user)  }}"
      template_group: "{{ template.group | default(role_component.group) }}"
      template_mode:  "{{ template.mode  | default(role_component.mode)  }}"
      template_type:  "{{ template.type  | default('jinja')  }}"
      template_no_log: "{{template.no_log| default(false)                }}"
      template_backup: "{{template.backup| default(role_component.backup)}}"
      template_become: "{{template.become| default(false)}}"
      var: "{{template.variables|default({})}}"
  - name: "[template] {{ template.name|upper }} template folder"
    file:
      path:  "{{ template_dest | dirname }}"
      state: directory
    # when: template_src
  - name: "[template] {{ template.name|upper }} template - {{ template_dest }} {{ template_owner }}:{{ template_group }} {{ template_mode }}"
    no_log:  "{{ template_no_log}}"
    template:
      src:   "{{ template_src   }}"
      dest:  "{{ template_dest  }}"
      owner: "{{ template_owner }}"
      group: "{{ template_group }}"
      mode:  "{{ template_mode  }}"
      backup: "{{ template_backup }}"
    become: "{{ template_become }}"
    # when: template_src
