---
- name: Converge
  hosts: all
  gather_facts: true
  remote_user: root
  tasks:
    - name: Update and upgrade apt packages
      shell: apt update
      become: true
    - ansible.builtin.include_role:
        name: components
      vars:
        role_component:
          components:
            - git
