---
- name: Converge
  hosts: all
  gather_facts: true
  remote_user: root
  tasks:
    - name: Testing -- git
      include_role:
        name: components
      vars:
        role_component:
          components: [git]
