---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_2004
    image: jgeusebroek/ubuntu2004-molecule
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
verifier:
  name: ansible
