---
- name: Converge
  hosts: all
  gather_facts: true
  remote_user: root
  tasks:
    # TODO: resolve deps
    - name: "Testing -- lastpass-cli"
      include_role:
        name: components
      vars:
        role_component:
          components:
            - brew
            - lastpass-cli
