---
# RUN CONFIGS
- block:
    - set_fact:
        run_config_prefix: '{{ prefix }}[run_config]'
        run_configs_templates: '{{ runConfigsObj.templates   | default([])  }}'
        handler_run_config: "{{ runConfigsObj.handler        | default('systemd_reload') }}"
        handler_run_config_variables: '{{ runConfigsObj.variables   | default([]) }}'
        handler_run_config_reload: '{{ runConfigsObj.handler_reload | default(name) }}'
        run_configs_pre: '{{ runConfigsObj.pre        | default([])  }}'
        run_configs_post: '{{ runConfigsObj.post       | default([])  }}'
    - debug:
        msg: '{{ runConfigsObj | to_nice_json }}'
        verbosity: 2
  # RUN-CONFIGS - PRE CMD
    - include_tasks: cmd.yml
      vars:
        type: pre
        prefix: run_configs
        content: '{{ run_configs_pre }}'
      when: run_configs_pre
  # RUN TEMPLATES: render via role_templates
    - name: '{{ run_config_prefix }} run configs'
      include_tasks: template.yml
      vars:
        handler_type: run
        handler_component: '{{ handler_run_config }}'
        handler_reload: '{{ handler_run_config_reload }}'
        var: '{{ handler_run_config_variables }}'
      with_items: ['{{ run_configs_templates }}']
      loop_control:
        loop_var: template
  # RUN-CONFIGS - POST CMD
    - include_tasks: cmd.yml
      vars:
        type: post
        prefix: run_configs
        content: '{{ run_configs_post }}'
      when: run_configs_post
    - meta: flush_handlers
  tags: run_configs
