galaxy_info:
  author: shellshock1953
  description: |-
    Role Components - one role to rule them all
  license: GPLv3
  min_ansible_version: "2.8"
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies: []
