---
role_component:
  brew:
    name: Brew - package manager for macOS or Linux
    install:
      pre:
        - name: '[brew] deps'
          package:
            name: "{{'{{'}} item {{'}}'}}"
            state: present
          loop: [git, curl]
          become: true
        - name: '[brew] get install script'
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
            dest: /tmp/install.sh
            mode: '0770'
        - name: '[brew] run install script'
          shell: /bin/bash /tmp/install.sh
          become: false
      post:
        - name: '[brew] version'
          shell: /home/linuxbrew/.linuxbrew/bin/brew --version
        - name: '[brew] install brew packages'
          community.general.homebrew:
            state: present
            name: []
             # - detect-secrets
             # - direnv
             # - ipcalc
             # - lastpass-cli
             # - lazygit
             # - pre-commit
             # - shellcheck
             # - terraform-docs
             # - tflint
