---
- name: Converge
  hosts: all
  gather_facts: true
  remote_user: root
  tasks:
    # TODO: resolve deps
    - name: Testing -- COMPONENT_NAME
      include_role:
        name: components
      vars:
        role_component:
          components: [COMPONENT_NAME]
