---
- name: Converge
  hosts: all
  gather_facts: true
  remote_user: root
  tasks:
    - shell: apt update
      become: true
    - name: "Testing dummy"
      include_role:
        name: components
      vars:
        role_component:
          components:
            - dummy
